---
- name: "Create volumes directories"
  file:
    path:   "{{ item }}"
    state:  directory
    owner:  root
    group:  root
    mode:   0755
  with_items:
    - /srv/gitlab
    - /srv/gitlab/config
    - /srv/gitlab/logs
    - /srv/gitlab/data
    - /srv/gitlab/logs/reconfigure
  tags:
    - dirs

- name: "Generate Marathon JSON description"
  template:
    src:  gitlab_marathon_app.json.j2
    dest: /tmp/gitlab_marathon_app.json
  delegate_to: localhost

- name: "Run Marathon app"
  uri:
    url:          "http://{{ domainname }}:8080/v2/apps/gitlab"
    method:       PUT
    body:         '{{ lookup("file", "/tmp/gitlab_marathon_app.json") }}'
    body_format:  json
    status_code:  "100,200,201,204"
    user:         horgix
    password:     verysecure
    HEADER_Content-Type:  "application/json"

- name: "Create Gitlab Group"
  delegate_to: 127.0.0.1
  gitlab_group:
    server_url:       "http://gitlab.svc.deploy.coffee"
    #validate_certs:   true
    login_user:       root
    login_password:   verysecure
    name:             xebia
    path:             xebia
    state:            present

