---
- name: "EC2 - Create instances"
  ec2:
    region: eu-west-1
    key_name: aws
    instance_type: "{{ item.type }}"
    # TODO : find_ami
    image: ami-f9dd458a
    wait: yes
    group: launch-wizard-1
    vpc_subnet_id: subnet-3adebc5e
    assign_public_ip: yes
    instance_tags: "{{ item.tags }}"
    exact_count: 1
    count_tag:
      type: "{{ item.tags.type }}"
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 20
  with_items: "{{ required_instances }}"
  register: newly_spawned

- name: "Wait for SSH to come up"
  wait_for:
    host: "{{ item.tagged_instances[0].public_dns_name }}"
    port: 22
    timeout:  320
    state: started
  with_items: "{{ newly_spawned.results }}"
