---
- name: "Set Zookeeper Nodes fact"
  set_fact:
    zk_nodes: "{% for host in groups['ec2'] %}{{ hostvars[host]['ec2_tag_zkid'] }}:{{ hostvars[host]['ec2_private_ip_address'] }}{% if not loop.last %},{% endif %}{% endfor %}"
    zk_nodes_with_port: "{% for host in groups['ec2'] %}{{ hostvars[host]['ec2_private_dns_name'] }}:2181{% if not loop.last %},{% endif %}{% endfor %}"
  tags:
    - always

# - name: "Zookeeper nodes"
#   debug:
#     msg: "{{ zk_nodes }}"
#   tags:
#     - always
#     - debug

- name: "Configure requirements"
  include: requirements.yml
  tags:
    - requirements

- name: "Configure Zookeeper"
  include: zookeeper.yml
  tags:
    - zookeeper
    - zk

- name: "Configure Mesos"
  include: mesos.yml
  tags:
    - mesos

- name: "Configure Marathon"
  include: marathon.yml
  tags:
    - marathon

#- name: "Configure Traefik"
#  include: traefik.yml
#  tags:
#    - traefik
#  when: ec2_tag_type != "svc"
