---
# ["ansible_default_ipv4"]["address"]
- name: "Configure requirements"
  include: requirements.yml
  tags:
    - requirements

- name: "Configure Zookeeper"
  include: zookeeper.yml
  tags:
    - zookeeper
    - zk

- name: "Configure Mesos"
  include: mesos.yml
  tags:
    - mesos

- name: "Configure Marathon"
  include: marathon.yml
  tags:
    - marathon

#- name: "Configure Traefik"
#  include: traefik.yml
#  tags:
#    - traefik
