---
- name: "Marathon - Start"
  docker_container:
    name:     marathon
    image:    mesoscloud/marathon
    state:    started
    recreate: yes
    network_mode: host
    # CF /usr/bin/marathon, l.98 for the reason of this ulimit
    ulimits:
      - "nofile:8192"
    ports:
      - "8080:8080"
    labels:
      traefik.enable:           "false"
      #traefik.port:           "8080"
      #traefik.backend:        "marathon"
      #traefik.frontend.rule:  "Host:{{ inventory_hostname }}"
    env:
      MARATHON_HOSTNAME:          "{{ inventory_hostname }}"
      MARATHON_HTTP_ADDRESS:      "{{ inventory_hostname }}"
      MARATHON_HTTP_CREDENTIALS:  "horgix:verysecure"
      MARATHON_ZK:                "zk://ip-172-31-9-253.eu-west-1.compute.internal:2181,ip-172-31-5-241.eu-west-1.compute.internal:2181,ip-172-31-4-250.eu-west-1.compute.internal:2181/marathon"
      MARATHON_MASTER:            "zk://ip-172-31-9-253.eu-west-1.compute.internal:2181,ip-172-31-5-241.eu-west-1.compute.internal:2181,ip-172-31-4-250.eu-west-1.compute.internal:2181/mesos"
