---
- name: "Zookeeper - Start"
  docker_container:
    name:         zookeeper
    image:        mesoscloud/zookeeper
    state:        started
    recreate:     yes
    network_mode: host
    #ports:
    #  - "2181:2181"
    #  - "2888:2888"
    #  - "3888:3888"
    labels:
      traefik.enable: "false"
    env:
      MYID:     "{{ id }}"
      SERVERS:  "ip-172-31-9-253.eu-west-1.compute.internal,ip-172-31-5-241.eu-west-1.compute.internal,ip-172-31-4-250.eu-west-1.compute.internal"
