---
- name: "Zookeeper - Start"
  docker_container:
    name:         zookeeper
    image:        horgix/zookeeper
    state:        started
    recreate:     yes
    network_mode: host
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    labels:
      traefik.enable: "false"
    env:
      MYID:     "{{ ec2_tag_zkid }}"
      SERVERS:  "{{ zk_nodes }}"
