---
- name: "Add Route 53 records"
  delegate_to: "127.0.0.1"
  connection: local
  route53:
    command: create
    zone: xebia.horgix.fr
    record: "{{ ec2_tag_type }}.xebia.horgix.fr"
    type: CNAME
    ttl: 60
    value: "{{ ec2_public_dns_name }}"
    overwrite: yes
    wait: yes

- name: "Add Route 53 records"
  delegate_to: "127.0.0.1"
  connection: local
  route53:
    command: create
    zone: xebia.horgix.fr
    record: "*.xebia.horgix.fr"
    type: CNAME
    ttl: 60
    value: "svc.xebia.horgix.fr"
    overwrite: yes
    wait: yes
  when: ec2_tag_type == "svc"
