---
- name: "Nuke GitLab"
  hosts: services
  tasks:
    - name: "Nuke GitLab volumes"
      file:
        path:   "{{ item }}"
        state:  absent
      with_items:
        - /srv/gitlab
        - /srv/gitlab/config
        - /srv/gitlab/logs
        - /srv/gitlab/data
        - /srv/gitlab/logs/reconfigure
      tags:
        - gitlab
    - name: "Nuke GitLab"
      uri:
        url:          "http://{{ instance_hostname }}:8080/v2/apps/gitlab"
        method:       DELETE
        user:         horgix
        password:     verysecure
        status_code:  "100,200,404"
        HEADER_Content-Type:  "application/json"
      tags:
        - gitlab

- name: "Nuke Traefik"
  hosts: services
  tasks:
    - name: "Nuke Traefik volumes"
      file:
        path:   "{{ item }}"
        state:  absent
      with_items:
        - /srv/traefik-marathon
      tags:
        - svctraefik
    - name: "Nuke Traefik"
      uri:
        url:          "http://{{ instance_hostname }}:8080/v2/apps/traefik"
        method:       DELETE
        user:         horgix
        password:     verysecure
        status_code:  "100,200,404"
        HEADER_Content-Type:  "application/json"
      tags:
        - svctraefik

- name: "Nuke Base"
  hosts: ec2
  tasks:
    - name: "Nuke Traefik"
      docker_container:
        name:         traefik
        state:        absent
        keep_volumes: False
      tags:
        - traefik
    - name: "Nuke Marathon"
      docker_container:
        name:         marathon
        state:        absent
        keep_volumes: False
      tags:
        - marathon
    - name: "Nuke Mesos master"
      docker_container:
        name:         mesos-master
        state:        absent
        keep_volumes: False
      tags:
        - mesos
        - mesos-master
    - name: "Nuke Mesos slave"
      docker_container:
        name:         mesos-slave
        state:        absent
        keep_volumes: False
      tags:
        - mesos
        - mesos-slave
    - name: "Nuke Zookeeper"
      docker_container:
        name:         zookeeper
        state:        absent
        keep_volumes: False
      tags:
        - zookeeper
