---
- name: "GitLab Runner - Get runners token"
  uri:
    url:          "{{ gitlab.endpoint }}/api/v3/projects/xebiafr%2Fclick-count"
    method:       GET
    status_code:  "100,200,201,204"
    HEADER_PRIVATE-TOKEN:  "{{ gitlab_private_token }}"
  register: api_project
  tags:
    - token

- name: "GitLab Runner - Set runners token as fact"
  set_fact:
    gitlab_runners_token:  "{{ api_project['json']['runners_token'] }}"
  tags:
    - token

- name: "GitLab Runner - Generate Marathon JSON description"
  template:
    src:  gitlab_runner_marathon_app.json.j2
    dest: /tmp/gitlab_runner_marathon_app.json
  delegate_to: localhost

- name: "Runner - Run Marathon app"
  uri:
    url:          "{{ marathon.endpoint }}/v2/apps/gitlab-runner"
    method:       PUT
    body:         '{{ lookup("file", "/tmp/gitlab_runner_marathon_app.json") }}'
    body_format:  json
    status_code:  "100,200,201,204"
    user:         "{{ marathon.username }}"
    password:     "{{ marathon.password }}"
    HEADER_Content-Type:  "application/json"
