---
- name: "Create Gitlab Group"
  delegate_to: 127.0.0.1
  gitlab_group:
    server_url:       "http://gitlab.{{ domain_name }}"
    #validate_certs:   true
    login_token:      "{{ gitlab_private_token }}"
    name:             xebiafr
    state:            present

- name: "Create Gitlab User"
  delegate_to: 127.0.0.1
  gitlab_user:
    server_url:       "http://gitlab.{{ domain_name }}"
    #validate_certs:   true
    login_token:      "{{ gitlab_private_token }}"
    name:             Xebia Interview
    username:         xebia
    password:         "{{ gitlab.xebia_password }}"
    group:            xebiafr
    access_level:     owner
    email:            alexis.horgix.chotard+xebia@gmail.com
    state:            present

- name: "Create Gitlab Project"
  delegate_to: 127.0.0.1
  gitlab_project:
    server_url:       "http://gitlab.{{ domain_name }}"
    #validate_certs:   true
    login_token:      "{{ gitlab_private_token }}"
    name:             click-count
    group:            xebiafr
    description:      Click Count application
    import_url:       "https://Horgix@bitbucket.org/Horgix/xebia-app.git"
    state:            present

- name: "Set variables"
  uri:
    url:          "http://gitlab.{{ domain_name }}/api/v3/projects/xebiafr%2Fclick-count/variables"
    method:       POST
    body:         "{{ item }}"
    status_code:  "200,201,400"
    HEADER_Content-Type: "application/x-www-form-urlencoded"
    HEADER_PRIVATE-TOKEN:  "{{ gitlab_private_token }}"
  with_items:
    - "key=HUB_LOGIN&value={{ docker_hub.username }}"
    - "key=HUB_PASSWORD&value={{ docker_hub.password }}"
    - "key=MARATHON_URL&value=http://{{ instance_hostname }}:8080"
    - "key=MARATHON_USERNAME&value={{ marathon.username }}"
    - "key=MARATHON_PASSWORD&value={{ marathon.password }}"
    - "key=STAGING_ENDPOINT&value=app.{{ instance_hostname }}"
    - "key=PRODUCTION_ENDPOINT&value=appprd.{{ instance_hostname }}"
