---
- name: "MesosUI - Generate Marathon JSON description"
  template:
    src:  mesosui_marathon_app.json.j2
    dest: /tmp/mesosui_marathon_app.json
  delegate_to: localhost

- name: "MesosUI - Run Marathon app"
  uri:
    url:          "http://{{ instance_hostname }}:8080/v2/apps/mesosui"
    method:       PUT
    body:         '{{ lookup("file", "/tmp/mesosui_marathon_app.json") }}'
    body_format:  json
    status_code:  "100,200,201,204"
    user:         horgix
    password:     verysecure
    HEADER_Content-Type:  "application/json"
